### ISSUE TITLE
Navigation files para navegación

### ISSUE THREAD

**Issue by josemontecastelo** [peigg/SkillForge#4]
https://github.com/peigg/SkillForge/blob/868e23671602d3b2b3d5eb3f565b81b5ef32753a/app/src/main/java/com/peigg/skillforge/navigation/AppNavigation.kt#L19

Es recomendable, como vimos en clase, crear archivos de navegación donde contener todo lo relacionado con la navegación y la ruta y así evitar tener las rutas hard-coded por el código.

En tu caso necesitarías los archivos StartScreenNavigation SkillForgeScreenNavigation

**Comment by peigg** [comment]
Cambio de la estructura de la aplicación para contener la lógica de navegación en archivos diferenciados.
